"""add intelligence_last_viewed_at to users

Revision ID: 5b197d512d15
Revises: 7493cf29304e
Create Date: 2026-09-16 03:44:47.211710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5b197d512d15'
down_revision: Union[str, None] = '7493cf29304e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('intelligence_last_viewed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'intelligence_last_viewed_at')
    # ### end Alembic commands ###
