"""add multi-source intelligence platform tables

Revision ID: 7493cf29304e
Revises: a0624dcdd5d6
Create Date: 2026-09-16 02:58:05.281179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '7493cf29304e'
down_revision: Union[str, None] = 'a0624dcdd5d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intelligence_sources',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('organization', sa.String(length=300), nullable=True),
    sa.Column('jurisdiction_level', sa.Enum('federal', 'state', 'local', 'regional', 'private', name='jurisdictionlevel', native_enum=False), nullable=False),
    sa.Column('geographic_coverage', sa.String(length=300), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('api_url', sa.String(length=1000), nullable=True),
    sa.Column('connector_type', sa.Enum('api', 'rss', 'structured_file', 'csv', 'html_scrape', 'pdf_parse', 'manual', name='connectortype', native_enum=False), nullable=False),
    sa.Column('connector_key', sa.String(length=60), nullable=True),
    sa.Column('requires_auth', sa.Boolean(), nullable=False),
    sa.Column('auth_notes', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('polling_frequency_hours', sa.Integer(), nullable=True),
    sa.Column('last_attempted_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_successful_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_result_count', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('health_status', sa.Enum('never_run', 'healthy', 'degraded', 'failing', 'needs_configuration', 'manual_only', name='sourcehealthstatus', native_enum=False), nullable=False),
    sa.Column('terms_notes', sa.Text(), nullable=True),
    sa.Column('parser_version', sa.String(length=20), nullable=True),
    sa.Column('default_intelligence_category', sa.Enum('live_opportunity', 'pre_solicitation', 'early_signal', 'award_intelligence', name='intelligencecategory', native_enum=False), nullable=True),
    sa.Column('naics_filter', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_intelligence_sources')),
    sa.UniqueConstraint('connector_key', name=op.f('uq_intelligence_sources_connector_key'))
    )
    op.create_index(op.f('ix_intelligence_sources_is_enabled'), 'intelligence_sources', ['is_enabled'], unique=False)
    op.create_index(op.f('ix_intelligence_sources_name'), 'intelligence_sources', ['name'], unique=True)
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by_user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_app_settings_updated_by_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_app_settings'))
    )
    op.create_table('intelligence_sync_runs',
    sa.Column('intelligence_source_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('running', 'success', 'partial_failure', 'failure', name='syncrunstatus', native_enum=False), nullable=False),
    sa.Column('items_fetched', sa.Integer(), nullable=False),
    sa.Column('items_created', sa.Integer(), nullable=False),
    sa.Column('items_updated', sa.Integer(), nullable=False),
    sa.Column('items_unchanged', sa.Integer(), nullable=False),
    sa.Column('items_errored', sa.Integer(), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('triggered_by', sa.Enum('manual', 'scheduled', name='synctriggeredby', native_enum=False), nullable=False),
    sa.Column('triggered_by_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['intelligence_source_id'], ['intelligence_sources.id'], name=op.f('fk_intelligence_sync_runs_intelligence_source_id_intelligence_sources'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['users.id'], name=op.f('fk_intelligence_sync_runs_triggered_by_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_intelligence_sync_runs'))
    )
    op.create_table('project_clusters',
    sa.Column('representative_title', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('confirmed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['confirmed_by_user_id'], ['users.id'], name=op.f('fk_project_clusters_confirmed_by_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_clusters'))
    )
    op.create_table('intelligence_items',
    sa.Column('intelligence_source_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('agency_name', sa.String(length=300), nullable=True),
    sa.Column('agency_id', sa.UUID(), nullable=True),
    sa.Column('jurisdiction_level', sa.Enum('federal', 'state', 'local', 'regional', 'private', name='jurisdictionlevel', native_enum=False), nullable=True),
    sa.Column('location_city', sa.String(length=120), nullable=True),
    sa.Column('location_state', sa.String(length=2), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('naics_code', sa.String(length=10), nullable=True),
    sa.Column('psc_code', sa.String(length=10), nullable=True),
    sa.Column('set_aside', sa.Enum('unrestricted', 'sdvosb', 'small_business', 'eight_a', 'hubzone', 'wosb', 'edwosb', 'other', name='setasidetype', native_enum=False), nullable=True),
    sa.Column('estimated_value_low', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('estimated_value_high', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('funding_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('proposal_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_solicitation_date', sa.Date(), nullable=True),
    sa.Column('estimated_award_date', sa.Date(), nullable=True),
    sa.Column('estimated_time_to_procurement', sa.Enum('months_0_3', 'months_3_6', 'months_6_12', 'months_12_24', 'unknown', name='estimatedtimetoprocurement', native_enum=False), nullable=True),
    sa.Column('maturity_stage', sa.Enum('rumored_conceptual', 'funding_identified', 'planning', 'procurement_forecast', 'sources_sought_rfi', 'solicitation_expected', 'solicitation_released', 'proposal_submitted', 'interview_negotiation', 'award_pending', 'awarded', name='maturitystage', native_enum=False), nullable=True),
    sa.Column('intelligence_category', sa.Enum('live_opportunity', 'pre_solicitation', 'early_signal', 'award_intelligence', name='intelligencecategory', native_enum=False), nullable=False),
    sa.Column('solicitation_number', sa.String(length=120), nullable=True),
    sa.Column('contract_number', sa.String(length=120), nullable=True),
    sa.Column('funding_award_number', sa.String(length=120), nullable=True),
    sa.Column('project_number', sa.String(length=120), nullable=True),
    sa.Column('incumbent_company_id', sa.UUID(), nullable=True),
    sa.Column('incumbent_name', sa.String(length=300), nullable=True),
    sa.Column('awardee_company_id', sa.UUID(), nullable=True),
    sa.Column('awardee_name', sa.String(length=300), nullable=True),
    sa.Column('is_prime_award', sa.Boolean(), nullable=True),
    sa.Column('relevant_disciplines', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('early_signal_score', sa.Integer(), nullable=True),
    sa.Column('early_signal_score_rationale', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('first_detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('opportunity_id', sa.UUID(), nullable=True),
    sa.Column('dedup_status', sa.Enum('unclustered', 'likely_duplicate', 'possible_duplicate', 'confirmed_same_project', name='dedupstatus', native_enum=False), nullable=False),
    sa.Column('project_cluster_id', sa.UUID(), nullable=True),
    sa.Column('dedup_match_reason', sa.Text(), nullable=True),
    sa.Column('is_sample_data', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confidence', sa.String(length=30), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], name=op.f('fk_intelligence_items_agency_id_agencies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['awardee_company_id'], ['companies.id'], name=op.f('fk_intelligence_items_awardee_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['incumbent_company_id'], ['companies.id'], name=op.f('fk_intelligence_items_incumbent_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['intelligence_source_id'], ['intelligence_sources.id'], name=op.f('fk_intelligence_items_intelligence_source_id_intelligence_sources'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('fk_intelligence_items_opportunity_id_opportunities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_cluster_id'], ['project_clusters.id'], name=op.f('fk_intelligence_items_project_cluster_id_project_clusters'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_intelligence_items')),
    sa.UniqueConstraint('intelligence_source_id', 'external_id', name='uq_intelligence_items_source_external_id'),
    comment='See docs/PHASE2_ARCHITECTURE.md §3'
    )
    op.create_index(op.f('ix_intelligence_items_external_id'), 'intelligence_items', ['external_id'], unique=False)
    op.create_index(op.f('ix_intelligence_items_intelligence_category'), 'intelligence_items', ['intelligence_category'], unique=False)
    op.create_index(op.f('ix_intelligence_items_is_sample_data'), 'intelligence_items', ['is_sample_data'], unique=False)
    op.create_index(op.f('ix_intelligence_items_location_state'), 'intelligence_items', ['location_state'], unique=False)
    op.create_index(op.f('ix_intelligence_items_proposal_due_at'), 'intelligence_items', ['proposal_due_at'], unique=False)
    op.create_index(op.f('ix_intelligence_items_solicitation_number'), 'intelligence_items', ['solicitation_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_intelligence_items_solicitation_number'), table_name='intelligence_items')
    op.drop_index(op.f('ix_intelligence_items_proposal_due_at'), table_name='intelligence_items')
    op.drop_index(op.f('ix_intelligence_items_location_state'), table_name='intelligence_items')
    op.drop_index(op.f('ix_intelligence_items_is_sample_data'), table_name='intelligence_items')
    op.drop_index(op.f('ix_intelligence_items_intelligence_category'), table_name='intelligence_items')
    op.drop_index(op.f('ix_intelligence_items_external_id'), table_name='intelligence_items')
    op.drop_table('intelligence_items')
    op.drop_table('project_clusters')
    op.drop_table('intelligence_sync_runs')
    op.drop_table('app_settings')
    op.drop_index(op.f('ix_intelligence_sources_name'), table_name='intelligence_sources')
    op.drop_index(op.f('ix_intelligence_sources_is_enabled'), table_name='intelligence_sources')
    op.drop_table('intelligence_sources')
    # ### end Alembic commands ###
