"""add status_board_syncs

Revision ID: 8dfbfb9cc829
Revises: e18608f60cfe
Create Date: 2026-09-29 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = '8dfbfb9cc829'
down_revision: Union[str, None] = 'e18608f60cfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'status_board_syncs',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('opportunity_id', sa.UUID(), nullable=False),
        sa.Column('status', sa.Enum('pending', 'synced', 'failed', name='statusboardsyncstatus', native_enum=False, length=20), nullable=False),
        sa.Column('sheet_row_number', sa.Integer(), nullable=True),
        sa.Column('attempt_count', sa.Integer(), nullable=False),
        sa.Column('last_error', sa.Text(), nullable=True),
        sa.Column('last_attempted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('fk_status_board_syncs_opportunity_id_opportunities'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_status_board_syncs')),
        sa.UniqueConstraint('opportunity_id', name=op.f('uq_status_board_syncs_opportunity_id')),
    )
    op.create_index(op.f('ix_status_board_syncs_status'), 'status_board_syncs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_status_board_syncs_status'), table_name='status_board_syncs')
    op.drop_table('status_board_syncs')
    # ### end Alembic commands ###
