"""initial schema

Revision ID: a0624dcdd5d6
Revises: 
Create Date: 2026-09-15 21:12:12.444731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'a0624dcdd5d6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agencies',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=True),
    sa.Column('agency_type', sa.String(length=50), nullable=True),
    sa.Column('parent_agency_id', sa.UUID(), nullable=True),
    sa.Column('priority_tier', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_sample_data', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_agency_id'], ['agencies.id'], name=op.f('fk_agencies_parent_agency_id_agencies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agencies'))
    )
    op.create_index(op.f('ix_agencies_name'), 'agencies', ['name'], unique=True)
    op.create_table('companies',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('company_type', sa.Enum('own_firm', 'teaming_partner', 'competitor', 'prime', 'subconsultant', 'other', name='companytype', native_enum=False), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('headquarters_city', sa.String(length=120), nullable=True),
    sa.Column('headquarters_state', sa.String(length=2), nullable=True),
    sa.Column('other_locations', sa.Text(), nullable=True),
    sa.Column('naics_codes', sa.String(length=500), nullable=True),
    sa.Column('technical_specialties', sa.Text(), nullable=True),
    sa.Column('is_sdvosb', sa.Boolean(), nullable=False),
    sa.Column('is_vosb', sa.Boolean(), nullable=False),
    sa.Column('is_hubzone', sa.Boolean(), nullable=False),
    sa.Column('is_eight_a', sa.Boolean(), nullable=False),
    sa.Column('is_wosb', sa.Boolean(), nullable=False),
    sa.Column('is_edwosb', sa.Boolean(), nullable=False),
    sa.Column('is_dbe', sa.Boolean(), nullable=False),
    sa.Column('is_small_business', sa.Boolean(), nullable=False),
    sa.Column('federal_experience_summary', sa.Text(), nullable=True),
    sa.Column('agencies_served', sa.Text(), nullable=True),
    sa.Column('contract_vehicles', sa.Text(), nullable=True),
    sa.Column('relationship_strength', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_sample_data', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies'))
    )
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_table('disciplines',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_disciplines')),
    sa.UniqueConstraint('name', name=op.f('uq_disciplines_name'))
    )
    op.create_table('naics_codes',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('is_core_market', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_naics_codes'))
    )
    op.create_index(op.f('ix_naics_codes_code'), 'naics_codes', ['code'], unique=True)
    op.create_table('pipeline_stages',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_closed_won', sa.Boolean(), nullable=False),
    sa.Column('is_closed_lost', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pipeline_stages')),
    sa.UniqueConstraint('name', name=op.f('uq_pipeline_stages_name'))
    )
    op.create_table('revenue_targets',
    sa.Column('period_label', sa.String(length=20), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_revenue_targets')),
    sa.UniqueConstraint('period_label', name=op.f('uq_revenue_targets_period_label'))
    )
    op.create_table('scoring_weight_profiles',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('weights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('geographic_priorities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('agency_priority_tiers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scoring_weight_profiles'))
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('administrator', 'executive', 'business_development', 'project_manager', 'proposal_manager', 'viewer', name='userrole', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('agency_offices',
    sa.Column('agency_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], name=op.f('fk_agency_offices_agency_id_agencies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agency_offices'))
    )
    op.create_table('alert_rules',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('new_matching_opportunity', 'new_sources_sought', 'deadline_approaching', 'opportunity_amended', 'gonogo_needed', 'task_due', 'recompete_approaching', 'other', name='alertcategory', native_enum=False), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('deliver_in_app', sa.Boolean(), nullable=False),
    sa.Column('deliver_email', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_alert_rules_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_rules'))
    )
    op.create_table('contacts',
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('agency_id', sa.UUID(), nullable=True),
    sa.Column('agency_office_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.Enum('contracting_officer', 'program_manager', 'small_business_specialist', 'technical_contact', 'agency_engineer', 'teaming_partner_contact', 'municipal_official', 'other', name='contactrole', native_enum=False), nullable=False),
    sa.Column('relationship_strength', sa.Integer(), nullable=True),
    sa.Column('last_contact_date', sa.Date(), nullable=True),
    sa.Column('next_follow_up_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], name=op.f('fk_contacts_agency_id_agencies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['agency_office_id'], ['agency_offices.id'], name=op.f('fk_contacts_agency_office_id_agency_offices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_contacts_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contacts'))
    )
    op.create_index(op.f('ix_contacts_full_name'), 'contacts', ['full_name'], unique=False)
    op.create_table('opportunities',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('agency_id', sa.UUID(), nullable=True),
    sa.Column('agency_office_id', sa.UUID(), nullable=True),
    sa.Column('solicitation_number', sa.String(length=120), nullable=True),
    sa.Column('location_city', sa.String(length=120), nullable=True),
    sa.Column('location_state', sa.String(length=2), nullable=True),
    sa.Column('naics_code', sa.String(length=10), nullable=True),
    sa.Column('psc_code', sa.String(length=10), nullable=True),
    sa.Column('set_aside', sa.Enum('unrestricted', 'sdvosb', 'small_business', 'eight_a', 'hubzone', 'wosb', 'edwosb', 'other', name='setasidetype', native_enum=False), nullable=False),
    sa.Column('contract_type', sa.Enum('ae_brooks_act', 'idiq', 'matoc', 'satoc', 'task_order', 'design_build', 'construction', 'other', name='contracttype', native_enum=False), nullable=False),
    sa.Column('estimated_value_low', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('estimated_value_high', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('estimated_fee', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('contract_duration_months', sa.Integer(), nullable=True),
    sa.Column('proposal_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('questions_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('site_visit_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('industry_day_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sources_sought_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('incumbent_company_id', sa.UUID(), nullable=True),
    sa.Column('incumbent_notes', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scope_summary', sa.Text(), nullable=True),
    sa.Column('evaluation_factors', sa.Text(), nullable=True),
    sa.Column('past_performance_requirements', sa.Text(), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('opportunity_source_label', sa.String(length=120), nullable=False),
    sa.Column('pipeline_stage_id', sa.UUID(), nullable=True),
    sa.Column('maturity_stage', sa.Enum('rumored_conceptual', 'funding_identified', 'planning', 'procurement_forecast', 'sources_sought_rfi', 'solicitation_expected', 'solicitation_released', 'proposal_submitted', 'interview_negotiation', 'award_pending', 'awarded', name='maturitystage', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('active', 'archived', name='opportunitystatus', native_enum=False), nullable=False),
    sa.Column('is_sdvosb_setaside', sa.Boolean(), nullable=False),
    sa.Column('is_sample_data', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('assigned_user_id', sa.UUID(), nullable=True),
    sa.Column('external_notice_id', sa.String(length=120), nullable=True),
    sa.Column('locked_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], name=op.f('fk_opportunities_agency_id_agencies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['agency_office_id'], ['agency_offices.id'], name=op.f('fk_opportunities_agency_office_id_agency_offices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], name=op.f('fk_opportunities_assigned_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_opportunities_created_by_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['incumbent_company_id'], ['companies.id'], name=op.f('fk_opportunities_incumbent_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pipeline_stage_id'], ['pipeline_stages.id'], name=op.f('fk_opportunities_pipeline_stage_id_pipeline_stages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_opportunities'))
    )
    op.create_index(op.f('ix_opportunities_external_notice_id'), 'opportunities', ['external_notice_id'], unique=False)
    op.create_index(op.f('ix_opportunities_is_sample_data'), 'opportunities', ['is_sample_data'], unique=False)
    op.create_index(op.f('ix_opportunities_is_sdvosb_setaside'), 'opportunities', ['is_sdvosb_setaside'], unique=False)
    op.create_index(op.f('ix_opportunities_location_state'), 'opportunities', ['location_state'], unique=False)
    op.create_index(op.f('ix_opportunities_proposal_due_at'), 'opportunities', ['proposal_due_at'], unique=False)
    op.create_index(op.f('ix_opportunities_set_aside'), 'opportunities', ['set_aside'], unique=False)
    op.create_index(op.f('ix_opportunities_solicitation_number'), 'opportunities', ['solicitation_number'], unique=False)
    op.create_index(op.f('ix_opportunities_title'), 'opportunities', ['title'], unique=False)
    op.create_table('activities',
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('activity_type', sa.Enum('created', 'stage_changed', 'score_recalculated', 'field_updated', 'document_uploaded', 'ai_analysis_completed', 'gonogo_started', 'gonogo_decided', 'task_created', 'task_completed', 'note', 'ingested', 'amended', name='activitytype', native_enum=False), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_activities_actor_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('fk_activities_opportunity_id_opportunities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activities'))
    )
    op.create_table('alerts',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.Enum('new_matching_opportunity', 'new_sources_sought', 'deadline_approaching', 'opportunity_amended', 'gonogo_needed', 'task_due', 'recompete_approaching', 'other', name='alertcategory', native_enum=False), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('opportunity_id', sa.UUID(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('email_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('fk_alerts_opportunity_id_opportunities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_alerts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts'))
    )
    op.create_index(op.f('ix_alerts_is_read'), 'alerts', ['is_read'], unique=False)
    op.create_table('gonogo_reviews',
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('ai_recommendation', sa.String(length=30), nullable=True),
    sa.Column('ai_recommendation_rationale', sa.Text(), nullable=True),
    sa.Column('decision', sa.Enum('go', 'conditional_go', 'no_go', name='gonogooutcome', native_enum=False), nullable=True),
    sa.Column('decided_by_id', sa.UUID(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], name=op.f('fk_gonogo_reviews_decided_by_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('fk_gonogo_reviews_opportunity_id_opportunities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gonogo_reviews'))
    )
    op.create_table('opportunity_companies',
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.Enum('incumbent', 'teaming_partner', 'confirmed_competitor', 'historical_competitor', 'likely_competitor', 'possible_competitor', 'subconsultant', 'prime', name='opportunitycompanyrelationship', native_enum=False), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('confidence', sa.String(length=30), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_opportunity_companies_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('fk_opportunity_companies_opportunity_id_opportunities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_opportunity_companies'))
    )
    op.create_table('opportunity_contacts',
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('role_on_opportunity', sa.Enum('contracting_officer', 'program_manager', 'small_business_specialist', 'technical_contact', 'agency_engineer', 'teaming_partner_contact', 'municipal_official', 'other', name='contactrole', native_enum=False), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_opportunity_contacts_contact_id_contacts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('fk_opportunity_contacts_opportunity_id_opportunities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_opportunity_contacts'))
    )
    op.create_table('opportunity_disciplines',
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('discipline_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['discipline_id'], ['disciplines.id'], name=op.f('fk_opportunity_disciplines_discipline_id_disciplines'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('fk_opportunity_disciplines_opportunity_id_opportunities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_opportunity_disciplines'))
    )
    op.create_table('opportunity_documents',
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('solicitation', 'amendment', 'scope', 'plans', 'agency_document', 'proposal_draft', 'sf330', 'teaming_agreement', 'resume', 'project_sheet', 'debrief', 'award_document', 'other', name='documentcategory', native_enum=False), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('replaces_document_id', sa.UUID(), nullable=True),
    sa.Column('uploaded_by_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('fk_opportunity_documents_opportunity_id_opportunities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['replaces_document_id'], ['opportunity_documents.id'], name=op.f('fk_opportunity_documents_replaces_document_id_opportunity_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], name=op.f('fk_opportunity_documents_uploaded_by_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_opportunity_documents'))
    )
    op.create_table('opportunity_scores',
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('weight_profile_id', sa.UUID(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('band', sa.String(length=20), nullable=False),
    sa.Column('category_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('category_rationale', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('why_it_scores_highly', sa.Text(), nullable=False),
    sa.Column('primary_concern', sa.Text(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('fk_opportunity_scores_opportunity_id_opportunities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['weight_profile_id'], ['scoring_weight_profiles.id'], name=op.f('fk_opportunity_scores_weight_profile_id_scoring_weight_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_opportunity_scores'))
    )
    op.create_table('opportunity_sources',
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confidence', sa.String(length=30), nullable=False),
    sa.Column('raw_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('fk_opportunity_sources_opportunity_id_opportunities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_opportunity_sources'))
    )
    op.create_table('revenue_forecasts',
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('total_contract_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('principal_share_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('estimated_fee', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('win_probability_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('expected_award_date', sa.Date(), nullable=True),
    sa.Column('expected_revenue_start', sa.Date(), nullable=True),
    sa.Column('expected_revenue_end', sa.Date(), nullable=True),
    sa.Column('market_sector', sa.String(length=120), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('fk_revenue_forecasts_opportunity_id_opportunities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_revenue_forecasts'))
    )
    op.create_table('tasks',
    sa.Column('opportunity_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'urgent', name='taskpriority', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('open', 'in_progress', 'completed', 'cancelled', name='taskstatus', native_enum=False), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_tasks_created_by_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('fk_tasks_opportunity_id_opportunities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_tasks_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    op.create_index(op.f('ix_tasks_due_date'), 'tasks', ['due_date'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_table('win_loss_reviews',
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('winner_company_id', sa.UUID(), nullable=True),
    sa.Column('winning_team_notes', sa.Text(), nullable=True),
    sa.Column('award_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('decision_date', sa.Date(), nullable=True),
    sa.Column('why_won_lost', sa.Text(), nullable=True),
    sa.Column('debrief_notes', sa.Text(), nullable=True),
    sa.Column('evaluation_scores_notes', sa.Text(), nullable=True),
    sa.Column('relationship_strength_notes', sa.Text(), nullable=True),
    sa.Column('technical_weaknesses', sa.Text(), nullable=True),
    sa.Column('proposal_weaknesses', sa.Text(), nullable=True),
    sa.Column('pricing_issues', sa.Text(), nullable=True),
    sa.Column('past_performance_gaps', sa.Text(), nullable=True),
    sa.Column('recorded_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('fk_win_loss_reviews_opportunity_id_opportunities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], name=op.f('fk_win_loss_reviews_recorded_by_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['winner_company_id'], ['companies.id'], name=op.f('fk_win_loss_reviews_winner_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_win_loss_reviews'))
    )
    op.create_table('ai_solicitation_analyses',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('model_used', sa.String(length=120), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('executive_summary', sa.Text(), nullable=True),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('deliverables', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('required_disciplines', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('relevant_naics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('contract_type', sa.String(length=120), nullable=True),
    sa.Column('evaluation_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('page_limits', sa.String(length=255), nullable=True),
    sa.Column('required_forms', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('key_personnel_requirements', sa.Text(), nullable=True),
    sa.Column('past_performance_requirements', sa.Text(), nullable=True),
    sa.Column('submission_instructions', sa.Text(), nullable=True),
    sa.Column('deadline', sa.String(length=120), nullable=True),
    sa.Column('questions_deadline', sa.String(length=120), nullable=True),
    sa.Column('site_visit', sa.String(length=255), nullable=True),
    sa.Column('interview_requirements', sa.Text(), nullable=True),
    sa.Column('small_business_requirements', sa.Text(), nullable=True),
    sa.Column('subcontracting_requirements', sa.Text(), nullable=True),
    sa.Column('licensing_requirements', sa.Text(), nullable=True),
    sa.Column('geographic_restrictions', sa.Text(), nullable=True),
    sa.Column('top_10_things_to_know', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('red_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_model_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['opportunity_documents.id'], name=op.f('fk_ai_solicitation_analyses_document_id_opportunity_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('fk_ai_solicitation_analyses_opportunity_id_opportunities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_solicitation_analyses'))
    )
    op.create_table('gonogo_criteria_scores',
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('criterion', sa.String(length=120), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['gonogo_reviews.id'], name=op.f('fk_gonogo_criteria_scores_review_id_gonogo_reviews'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gonogo_criteria_scores'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gonogo_criteria_scores')
    op.drop_table('ai_solicitation_analyses')
    op.drop_table('win_loss_reviews')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_due_date'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_table('revenue_forecasts')
    op.drop_table('opportunity_sources')
    op.drop_table('opportunity_scores')
    op.drop_table('opportunity_documents')
    op.drop_table('opportunity_disciplines')
    op.drop_table('opportunity_contacts')
    op.drop_table('opportunity_companies')
    op.drop_table('gonogo_reviews')
    op.drop_index(op.f('ix_alerts_is_read'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_table('activities')
    op.drop_index(op.f('ix_opportunities_title'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_solicitation_number'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_set_aside'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_proposal_due_at'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_location_state'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_is_sdvosb_setaside'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_is_sample_data'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_external_notice_id'), table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_index(op.f('ix_contacts_full_name'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_table('alert_rules')
    op.drop_table('agency_offices')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('scoring_weight_profiles')
    op.drop_table('revenue_targets')
    op.drop_table('pipeline_stages')
    op.drop_index(op.f('ix_naics_codes_code'), table_name='naics_codes')
    op.drop_table('naics_codes')
    op.drop_table('disciplines')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_agencies_name'), table_name='agencies')
    op.drop_table('agencies')
    # ### end Alembic commands ###
