"""add diagnostics to intelligence_sync_runs

Revision ID: bc3745da611f
Revises: 5b197d512d15
Create Date: 2026-09-16 15:43:11.905811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'bc3745da611f'
down_revision: Union[str, None] = '5b197d512d15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intelligence_sync_runs', sa.Column('diagnostics', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('intelligence_sync_runs', 'diagnostics')
    # ### end Alembic commands ###
