"""add sam relevance score and rationale to intelligence_items

Revision ID: bfa343853aa1
Revises: bc3745da611f
Create Date: 2026-09-16 15:58:51.335986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'bfa343853aa1'
down_revision: Union[str, None] = 'bc3745da611f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intelligence_items', sa.Column('sam_relevance_score', sa.Integer(), nullable=True))
    op.add_column('intelligence_items', sa.Column('sam_relevance_rationale', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('intelligence_items', 'sam_relevance_rationale')
    op.drop_column('intelligence_items', 'sam_relevance_score')
    # ### end Alembic commands ###
