"""add grants relevance score and rationale to intelligence_items

Revision ID: e18608f60cfe
Revises: bfa343853aa1
Create Date: 2026-09-16 19:44:07.724481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'e18608f60cfe'
down_revision: Union[str, None] = 'bfa343853aa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intelligence_items', sa.Column('grants_relevance_score', sa.Integer(), nullable=True))
    op.add_column('intelligence_items', sa.Column('grants_relevance_rationale', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('intelligence_items', 'grants_relevance_rationale')
    op.drop_column('intelligence_items', 'grants_relevance_score')
    # ### end Alembic commands ###
